name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  DevelopDebug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Clear Gradle Build Cache
      uses: gradle/gradle-build-action@v2
      with:
         arguments: clean
        
    - name: Build debug APK
      uses: gradle/gradle-build-action@v2
      with:
          arguments: assembleDevelopDebug
      env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
          name: apk-develop-debug
          path: app/build/outputs/apk/develop/debug
